-- ==========================================================
-- Raja Electricals - Supabase Schema & Initial Setup
-- Project ID: xgtwlxycixgzhjyfcksb (ap-southeast-2)
-- ==========================================================

-- 1. SITE SETTINGS TABLE
CREATE TABLE IF NOT EXISTS public.site_settings (
  id INT PRIMARY KEY DEFAULT 1,
  data JSONB DEFAULT '{}'::jsonb,
  updated_at TIMESTAMPTZ DEFAULT now()
);

-- 2. PRODUCTS TABLE
CREATE TABLE IF NOT EXISTS public.products (
  id TEXT PRIMARY KEY,
  name TEXT,
  category TEXT,
  subcategory TEXT,
  description TEXT,
  price TEXT,
  badge TEXT,
  image TEXT,
  features TEXT,
  specifications TEXT,
  colors TEXT,
  catalog_name TEXT,
  catalog_url TEXT,
  data JSONB DEFAULT '{}'::jsonb,
  created_at TIMESTAMPTZ DEFAULT now(),
  updated_at TIMESTAMPTZ DEFAULT now()
);

-- 3. CATEGORIES TABLE
CREATE TABLE IF NOT EXISTS public.categories (
  id TEXT PRIMARY KEY,
  name TEXT,
  count TEXT,
  image TEXT,
  data JSONB DEFAULT '{}'::jsonb,
  created_at TIMESTAMPTZ DEFAULT now(),
  updated_at TIMESTAMPTZ DEFAULT now()
);

-- 4. BRANDS TABLE
CREATE TABLE IF NOT EXISTS public.brands (
  id TEXT PRIMARY KEY,
  name TEXT,
  category TEXT,
  products TEXT,
  description TEXT,
  logo TEXT,
  data JSONB DEFAULT '{}'::jsonb,
  created_at TIMESTAMPTZ DEFAULT now(),
  updated_at TIMESTAMPTZ DEFAULT now()
);

-- 5. INDUSTRIES TABLE
CREATE TABLE IF NOT EXISTS public.industries (
  id TEXT PRIMARY KEY,
  name TEXT,
  description TEXT,
  image TEXT,
  data JSONB DEFAULT '{}'::jsonb,
  created_at TIMESTAMPTZ DEFAULT now(),
  updated_at TIMESTAMPTZ DEFAULT now()
);

-- 6. PROJECTS TABLE
CREATE TABLE IF NOT EXISTS public.projects (
  id TEXT PRIMARY KEY,
  name TEXT,
  category TEXT,
  location TEXT,
  year TEXT,
  products TEXT,
  description TEXT,
  image TEXT,
  data JSONB DEFAULT '{}'::jsonb,
  created_at TIMESTAMPTZ DEFAULT now(),
  updated_at TIMESTAMPTZ DEFAULT now()
);

-- 7. GALLERY TABLE
CREATE TABLE IF NOT EXISTS public.gallery (
  id TEXT PRIMARY KEY,
  title TEXT,
  type TEXT,
  image TEXT,
  data JSONB DEFAULT '{}'::jsonb,
  created_at TIMESTAMPTZ DEFAULT now(),
  updated_at TIMESTAMPTZ DEFAULT now()
);

-- 8. ENQUIRIES TABLE
CREATE TABLE IF NOT EXISTS public.enquiries (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  data JSONB DEFAULT '{}'::jsonb,
  created_at TIMESTAMPTZ DEFAULT now()
);

-- 9. ORDERS TABLE
CREATE TABLE IF NOT EXISTS public.orders (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  data JSONB DEFAULT '{}'::jsonb,
  created_at TIMESTAMPTZ DEFAULT now()
);

-- 10. CATALOGUES TABLE
CREATE TABLE IF NOT EXISTS public.catalogues (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  data JSONB DEFAULT '{}'::jsonb,
  created_at TIMESTAMPTZ DEFAULT now()
);

-- 11. ADMINS TABLE
CREATE TABLE IF NOT EXISTS public.admins (
  email TEXT PRIMARY KEY,
  password_hash TEXT,
  data JSONB DEFAULT '{}'::jsonb,
  created_at TIMESTAMPTZ DEFAULT now()
);

-- ==========================================================
-- ROW LEVEL SECURITY (RLS) POLICIES
-- ==========================================================

ALTER TABLE public.site_settings ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.products ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.categories ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.brands ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.industries ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.projects ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.gallery ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.enquiries ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.orders ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.catalogues ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.admins ENABLE ROW LEVEL SECURITY;

-- Allow public read access to catalog data
CREATE POLICY "Public read site_settings" ON public.site_settings FOR SELECT USING (true);
CREATE POLICY "Public read products" ON public.products FOR SELECT USING (true);
CREATE POLICY "Public read categories" ON public.categories FOR SELECT USING (true);
CREATE POLICY "Public read brands" ON public.brands FOR SELECT USING (true);
CREATE POLICY "Public read industries" ON public.industries FOR SELECT USING (true);
CREATE POLICY "Public read projects" ON public.projects FOR SELECT USING (true);
CREATE POLICY "Public read gallery" ON public.gallery FOR SELECT USING (true);

-- Allow public customer submissions
CREATE POLICY "Public insert enquiries" ON public.enquiries FOR INSERT WITH CHECK (true);
CREATE POLICY "Public insert orders" ON public.orders FOR INSERT WITH CHECK (true);

-- Allow service_role full access to all tables
CREATE POLICY "Service full site_settings" ON public.site_settings FOR ALL TO service_role USING (true) WITH CHECK (true);
CREATE POLICY "Service full products" ON public.products FOR ALL TO service_role USING (true) WITH CHECK (true);
CREATE POLICY "Service full categories" ON public.categories FOR ALL TO service_role USING (true) WITH CHECK (true);
CREATE POLICY "Service full brands" ON public.brands FOR ALL TO service_role USING (true) WITH CHECK (true);
CREATE POLICY "Service full industries" ON public.industries FOR ALL TO service_role USING (true) WITH CHECK (true);
CREATE POLICY "Service full projects" ON public.projects FOR ALL TO service_role USING (true) WITH CHECK (true);
CREATE POLICY "Service full gallery" ON public.gallery FOR ALL TO service_role USING (true) WITH CHECK (true);
CREATE POLICY "Service full enquiries" ON public.enquiries FOR ALL TO service_role USING (true) WITH CHECK (true);
CREATE POLICY "Service full orders" ON public.orders FOR ALL TO service_role USING (true) WITH CHECK (true);
CREATE POLICY "Service full catalogues" ON public.catalogues FOR ALL TO service_role USING (true) WITH CHECK (true);
CREATE POLICY "Service full admins" ON public.admins FOR ALL TO service_role USING (true) WITH CHECK (true);

-- ==========================================================
-- SEED DEFAULT ADMIN USER
-- Email: admin@rajaelectricals.com
-- Password: raja@123456
-- ==========================================================
INSERT INTO public.admins (email, password_hash, data)
VALUES (
  'admin@rajaelectricals.com',
  '$2b$12$S43SRuxrKIxxjaw6IqIx1eYgO.9NVWqeCPD8ZLh2ZQloyJwoxmZPC',
  '{"email": "admin@rajaelectricals.com", "role": "admin"}'::jsonb
)
ON CONFLICT (email) DO UPDATE
SET password_hash = EXCLUDED.password_hash,
    data = EXCLUDED.data;
